### ISSUE TITLE
Missing Class Error

### ISSUE THREAD

**Issue by saboobaker** [pushbit/sprockets#16]
Called this API:
	Params params = Params.create().latitude(latitude).longitude(longitude).keyword(name);
        Response<List<Place>> resp = Places.nearbySearch(params);

When executing search, it throws class not found exception with following stack trace:
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/internal/http/RequestException
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:29)
	at com.squareup.okhttp.OkUrlFactory.open(OkUrlFactory.java:57)
	at com.squareup.okhttp.OkUrlFactory.open(OkUrlFactory.java:48)
	at net.sf.sprockets.net.HttpClient.openConnection(HttpClient.java:72)
	at net.sf.sprockets.net.HttpClient.openConnection(HttpClient.java:65)
	at net.sf.sprockets.google.Places.reader(Places.java:833)
	at net.sf.sprockets.google.Places.places(Places.java:799)
	at net.sf.sprockets.google.Places.nearbySearch(Places.java:262)
	at net.sf.sprockets.google.Places.nearbySearch(Places.java:215)

**Comment by pushbit** [comment]
Have you manually added a version of okhttp to your dependencies?  The library uses version 2.6.0, which does have `RequestException`.  I see that they made some breaking changes in 3.x and this might be related.  When I have time I will upgrade the library to use 3.x.

**Comment by pushbit** [comment]
Please try again with 3.1.0.  If you are still having the same problem, please create a simple example that will allow me to reproduce it.
